using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;

// Builds the "Statue Garden" scene (draped portrait bust and an autumn tree): Tools > Build Statue Scene.
public static class StatueSceneBuilder
{
    const string ScenePath = "Assets/Scenes/StatueGarden.unity";
    const string MaterialFolder = "Assets/Materials";

    [MenuItem("Tools/Build Statue Scene")]
    public static void Build()
    {
        if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        var marble = GetMaterial("Marble", new Color(0.90f, 0.88f, 0.83f), 0.6f, 0f);
        var stone = GetMaterial("Stone", new Color(0.62f, 0.60f, 0.57f), 0.2f, 0f);
        var grass = GetMaterial("Grass", new Color(0.32f, 0.5f, 0.25f), 0.1f, 0f);
        var path = GetMaterial("Path", new Color(0.62f, 0.56f, 0.47f), 0.15f, 0f);

        // Lighting
        var sun = new GameObject("Sun").AddComponent<Light>();
        sun.type = LightType.Directional;
        sun.intensity = 1.3f;
        sun.shadows = LightShadows.Soft;
        sun.color = new Color(1f, 0.95f, 0.86f);
        sun.transform.rotation = Quaternion.Euler(45f, -35f, 0f);
        RenderSettings.ambientMode = AmbientMode.Trilight;
        RenderSettings.ambientSkyColor = new Color(0.55f, 0.65f, 0.8f);
        RenderSettings.ambientEquatorColor = new Color(0.45f, 0.45f, 0.42f);
        RenderSettings.ambientGroundColor = new Color(0.2f, 0.22f, 0.18f);

        // Ground and plaza
        var env = new GameObject("Environment").transform;
        Part(PrimitiveType.Plane, "Ground", env, Vector3.zero, new Vector3(6f, 1f, 6f), grass);
        Part(PrimitiveType.Cylinder, "Plaza", env, new Vector3(0f, 0.05f, 0f), new Vector3(22f, 0.05f, 22f), path);

        // Portrait bust wearing a marble drape, on a pedestal in front of the start
        var statues = new GameObject("Statues").transform;
        var bust = Bust("Bust_Portrait", statues, new Vector3(0f, 0f, -1.5f), marble, stone);

        // Autumn tree behind the bust (meshes generated by tools/statue_gen/autumn_tree.py)
        AutumnTree("AutumnTree", env, new Vector3(0f, 0.1f, 3f));

        // Camera looking at the plaza
        var cam = new GameObject("Main Camera");
        cam.tag = "MainCamera";
        cam.AddComponent<Camera>().fieldOfView = 60f;
        cam.AddComponent<AudioListener>();
        cam.AddComponent<FlyCamera>();
        // player eye height, looking past the bust to the tree
        cam.transform.position = new Vector3(0f, 1.7f, -4f);
        cam.transform.LookAt(bust.transform.position + Vector3.up * 1.6f);

        EditorSceneManager.SaveScene(scene, ScenePath);
        AddToBuildSettings(ScenePath);
        Debug.Log($"Statue scene built and saved to {ScenePath}");
    }

    const string TreeFolder = "Assets/Models/Trees";

    // Blender-built tree (tools/blender_tree): displaced bark with albedo + normal maps,
    // and maple-leaf cards cut out of a texture atlas with alpha clipping, rendered two-sided.
    static void AutumnTree(string name, Transform parent, Vector3 position)
    {
        var root = new GameObject(name);
        root.transform.SetParent(parent, false);
        root.transform.localPosition = position;

        var bark = GetMaterial("Bark", Color.white, 0.1f, 0f);
        bark.SetTexture("_BaseMap", LoadTexture($"{TreeFolder}/Textures/bark_albedo.png", false));
        bark.SetTexture("_BumpMap", LoadTexture($"{TreeFolder}/Textures/bark_normal.png", true));
        bark.EnableKeyword("_NORMALMAP");

        var leaves = GetMaterial("Leaves", Color.white, 0.3f, 0f);
        leaves.SetTexture("_BaseMap", LoadTexture($"{TreeFolder}/Textures/leaves_atlas.png", false));
        leaves.SetTexture("_BumpMap", LoadTexture($"{TreeFolder}/Textures/leaves_normal.png", true));
        leaves.EnableKeyword("_NORMALMAP");
        leaves.SetFloat("_AlphaClip", 1f);
        leaves.SetFloat("_Cutoff", 0.5f);
        leaves.EnableKeyword("_ALPHATEST_ON");
        leaves.SetFloat("_Cull", (float)CullMode.Off);
        leaves.doubleSidedGI = true;
        EditorUtility.SetDirty(leaves);

        var trunk = AddMesh(root.transform, "Bark", $"{TreeFolder}/Tree_Bark.fbx", bark);
        if (trunk != null)
            trunk.AddComponent<MeshCollider>().sharedMesh = trunk.GetComponent<MeshFilter>().sharedMesh;
        var crown = AddMesh(root.transform, "Leaves", $"{TreeFolder}/Tree_Leaves.fbx", leaves);
        if (crown != null)
        {
            var falling = root.AddComponent<FallingLeaves>();
            // the editor can read imported meshes; every 9th vertex spreads points over the whole crown
            var verts = crown.GetComponent<MeshFilter>().sharedMesh.vertices;
            falling.spawnPoints = new Vector3[verts.Length / 9];
            for (int i = 0; i < falling.spawnPoints.Length; i++)
                falling.spawnPoints[i] = verts[i * 9];
            falling.leafMaterial = leaves;
        }
        AddMesh(root.transform, "FallenLeaves", $"{TreeFolder}/Tree_FallenLeaves.fbx", leaves);
    }

    static Texture2D LoadTexture(string path, bool normalMap)
    {
        if (normalMap && AssetImporter.GetAtPath(path) is TextureImporter importer
            && importer.textureType != TextureImporterType.NormalMap)
        {
            importer.textureType = TextureImporterType.NormalMap;
            importer.SaveAndReimport();
        }
        var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
        if (tex == null)
            Debug.LogError($"Missing texture {path}");
        return tex;
    }

    static GameObject AddMesh(Transform parent, string name, string path, Material material)
    {
        var mesh = LoadMesh(path);
        if (mesh == null)
        {
            Debug.LogError($"Missing mesh {path}");
            return null;
        }
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        go.AddComponent<MeshFilter>().sharedMesh = mesh;
        go.AddComponent<MeshRenderer>().sharedMaterial = material;
        return go;
    }

    // A bust mesh (base at its origin, facing -Z) on a 1 m stone pedestal standing on the plaza.
    static GameObject Bust(string name, Transform parent, Vector3 position, Material marble, Material stone)
    {
        const float plaza = 0.1f, pedestal = 1f;
        var root = new GameObject(name).transform;
        root.SetParent(parent, false);
        root.localPosition = position;
        Part(PrimitiveType.Cube, "Pedestal", root, new Vector3(0f, plaza + pedestal / 2f, 0f), new Vector3(0.55f, pedestal, 0.45f), stone);

        var mesh = LoadMesh($"Assets/Models/Statues/{name}.obj");
        if (mesh == null)
        {
            Debug.LogError($"Missing bust mesh Assets/Models/Statues/{name}.obj");
            return root.gameObject;
        }
        var bust = new GameObject("Bust");
        bust.transform.SetParent(root, false);
        bust.transform.localPosition = new Vector3(0f, plaza + pedestal, 0f);
        bust.AddComponent<MeshFilter>().sharedMesh = mesh;
        bust.AddComponent<MeshRenderer>().sharedMaterial = marble;
        bust.AddComponent<MeshCollider>().sharedMesh = mesh;

        // optional marble cloth draped over the body
        var drapeMesh = LoadMesh($"Assets/Models/Statues/{name}_Drape.obj");
        if (drapeMesh != null)
        {
            var drape = new GameObject("Drape");
            drape.transform.SetParent(bust.transform, false);
            drape.AddComponent<MeshFilter>().sharedMesh = drapeMesh;
            drape.AddComponent<MeshRenderer>().sharedMaterial = marble;
        }
        return root.gameObject;
    }

    static Mesh LoadMesh(string path)
    {
        foreach (var asset in AssetDatabase.LoadAllAssetsAtPath(path))
            if (asset is Mesh mesh)
                return mesh;
        return null;
    }

    static GameObject Part(PrimitiveType type, string name, Transform parent, Vector3 pos, Vector3 scale, Material mat)
    {
        var go = GameObject.CreatePrimitive(type);
        go.name = name;
        go.transform.SetParent(parent, false);
        go.transform.localPosition = pos;
        go.transform.localScale = scale;
        go.GetComponent<Renderer>().sharedMaterial = mat;
        return go;
    }

    static Material GetMaterial(string name, Color color, float smoothness, float metallic)
    {
        if (!AssetDatabase.IsValidFolder(MaterialFolder))
            AssetDatabase.CreateFolder("Assets", "Materials");

        string assetPath = $"{MaterialFolder}/{name}.mat";
        var mat = AssetDatabase.LoadAssetAtPath<Material>(assetPath);
        if (mat == null)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            mat = new Material(shader);
            AssetDatabase.CreateAsset(mat, assetPath);
        }
        mat.SetColor("_BaseColor", color);
        mat.color = color;
        mat.SetFloat("_Smoothness", smoothness);
        mat.SetFloat("_Metallic", metallic);
        EditorUtility.SetDirty(mat);
        AssetDatabase.SaveAssets();
        return mat;
    }

    static void AddToBuildSettings(string path)
    {
        var scenes = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
        if (scenes.Exists(s => s.path == path)) return;
        scenes.Add(new EditorBuildSettingsScene(path, true));
        EditorBuildSettings.scenes = scenes.ToArray();
    }
}
