"""Mesh the veiled statue SDF, decimate to game LODs, export OBJ and render previews.

usage: python3 build.py [--voxel 0.0016] [--seed 1] [--name VeiledStatue_A] [--out DIR]
"""
import argparse
import os
import time
from multiprocessing import Pool

import fast_simplification
import numpy as np
import trimesh
from PIL import Image
from skimage.measure import marching_cubes

from veiled_statue import VeiledStatue

MODEL = None


def _init(kwargs, seed):
    global MODEL
    MODEL = VeiledStatue(**kwargs)
    MODEL.plan_damage(np.random.default_rng(seed))


def _slab(args):
    xs, ys, zs = args
    g = np.stack(np.meshgrid(xs, ys, zs, indexing="ij"), -1).reshape(-1, 3)
    return MODEL(g).reshape(len(xs), len(ys), len(zs)).astype(np.float32)


def evaluate(kwargs, seed, voxel):
    lo, hi = VeiledStatue.bounds_min, VeiledStatue.bounds_max
    xs, ys, zs = (np.arange(lo[i], hi[i] + voxel, voxel) for i in range(3))
    chunks = np.array_split(xs, max(1, len(xs) // 6))
    with Pool(os.cpu_count(), _init, (kwargs, seed)) as pool:
        vol = np.concatenate(pool.map(_slab, [(c, ys, zs) for c in chunks]), 0)
    return vol, lo


def to_mesh(vol, origin, voxel):
    v, f, _, _ = marching_cubes(vol, 0.0, spacing=(voxel,) * 3)
    m = trimesh.Trimesh(v + origin, f[:, ::-1], process=True)
    m.remove_unreferenced_vertices()
    parts = m.split(only_watertight=False)
    m = max(parts, key=lambda p: len(p.faces))  # drop floating crumbs
    if m.volume < 0:
        m.invert()
    return m


def decimate(m, tris):
    ratio = 1.0 - tris / len(m.faces)
    if ratio <= 0:
        return m
    v, f = fast_simplification.simplify(m.vertices.astype(np.float32), m.faces.astype(np.int32), ratio)
    return trimesh.Trimesh(v, f, process=True)


def write_obj(m, path, name):
    n = m.vertex_normals
    with open(path, "w") as fh:
        fh.write(f"# {name}: {len(m.faces)} triangles, generated by tools/statue_gen\no {name}\n")
        fh.write("".join(f"v {a:.5f} {b:.5f} {c:.5f}\n" for a, b, c in m.vertices))
        fh.write("".join(f"vn {a:.4f} {b:.4f} {c:.4f}\n" for a, b, c in n))
        fh.write("".join(f"f {a}//{a} {b}//{b} {c}//{c}\n" for a, b, c in m.faces + 1))


# --- preview renderer ---------------------------------------------------------

def cavity(m):
    """Per-vertex concavity from the umbrella Laplacian, used to darken cracks and holes."""
    nb = m.vertex_neighbors
    lap = np.array([m.vertices[list(x)].mean(0) if len(x) else m.vertices[i] for i, x in enumerate(nb)])
    c = np.einsum("ij,ij->i", lap - m.vertices, m.vertex_normals)
    for _ in range(3):
        c = np.array([c[list(x)].mean() if len(x) else c[i] for i, x in enumerate(nb)])
    return np.clip(c / (np.percentile(np.abs(c), 97) + 1e-9), -1, 1)


def render(m, path, yaw=0.0, pitch=8.0, size=900, target=None, zoom=1.0, colors=None):
    R = trimesh.transformations.euler_matrix(np.radians(pitch), np.radians(yaw), 0, "rxyz")[:3, :3]
    target = m.bounds.mean(0) if target is None else np.asarray(target)
    v = (m.vertices - target) @ R.T
    n = m.vertex_normals @ R.T
    scale = size * 0.9 / (np.ptp(m.vertices, 0).max()) * zoom
    sx = size / 2 + v[:, 0] * scale
    sy = size / 2 - v[:, 1] * scale
    depth = v[:, 2]  # camera looks along +z (statue faces -z)
    cav = cavity(m)

    L = np.array([-0.5, 0.65, -0.6]); L /= np.linalg.norm(L)
    L2 = np.array([0.7, 0.2, -0.3]); L2 /= np.linalg.norm(L2)
    ndl = n @ L if colors is None else np.abs(n @ L)  # coloured parts may be thin, two-sided leaves
    wrap = np.clip((ndl + 0.35) / 1.35, 0, 1)                       # soft marble wrap light
    fill = np.clip(n @ L2, 0, 1) * 0.25
    H = L + np.array([0, 0, -1.0]); H /= np.linalg.norm(H)
    spec = np.clip(n @ H, 0, 1) ** 40 * 0.25
    ao = np.clip(1.0 - 0.9 * np.maximum(cav, 0) + 0.08 * np.minimum(cav, 0), 0.3, 1.05)
    base = np.array([0.93, 0.90, 0.84]) if colors is None else colors
    sss = np.array([1.0, 0.88, 0.75])
    col = (base * (0.18 + 0.8 * wrap[:, None] + fill[:, None]) + sss * 0.06) * ao[:, None] + spec[:, None]

    zbuf = np.full((size, size), np.inf)
    img = np.zeros((size, size, 3))
    for a, b, c in m.faces:
        x0, x1 = int(max(min(sx[a], sx[b], sx[c]), 0)), int(min(max(sx[a], sx[b], sx[c]) + 1, size - 1))
        y0, y1 = int(max(min(sy[a], sy[b], sy[c]), 0)), int(min(max(sy[a], sy[b], sy[c]) + 1, size - 1))
        if x1 < x0 or y1 < y0:
            continue
        X, Y = np.meshgrid(np.arange(x0, x1 + 1) + 0.5, np.arange(y0, y1 + 1) + 0.5)
        d = (sy[b] - sy[c]) * (sx[a] - sx[c]) + (sx[c] - sx[b]) * (sy[a] - sy[c])
        if abs(d) < 1e-12:
            continue
        w0 = ((sy[b] - sy[c]) * (X - sx[c]) + (sx[c] - sx[b]) * (Y - sy[c])) / d
        w1 = ((sy[c] - sy[a]) * (X - sx[c]) + (sx[a] - sx[c]) * (Y - sy[c])) / d
        w2 = 1 - w0 - w1
        inside = (w0 >= 0) & (w1 >= 0) & (w2 >= 0)
        if not inside.any():
            continue
        z = w0 * depth[a] + w1 * depth[b] + w2 * depth[c]
        zb = zbuf[y0:y1 + 1, x0:x1 + 1]
        upd = inside & (z < zb)
        zb[upd] = z[upd]
        shade = w0[..., None] * col[a] + w1[..., None] * col[b] + w2[..., None] * col[c]
        img[y0:y1 + 1, x0:x1 + 1][upd] = shade[upd]
    bg = np.linspace(0.30, 0.18, size)[:, None, None] * np.array([0.75, 0.8, 0.85])
    img = np.where(np.isinf(zbuf)[..., None], bg, img)
    Image.fromarray((np.clip(img, 0, 1) ** (1 / 1.1) * 255).astype(np.uint8)).save(path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--voxel", type=float, default=0.0022)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--yaw", type=float, default=18.0)
    ap.add_argument("--pitch", type=float, default=16.0)
    ap.add_argument("--roll", type=float, default=8.0)
    ap.add_argument("--name", default="VeiledStatue_A")
    ap.add_argument("--out", default="out")
    ap.add_argument("--lods", default="150000,50000,15000")
    ap.add_argument("--preview", default="")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    t = time.time()
    kw = dict(seed=args.seed, head_yaw=args.yaw, head_pitch=args.pitch, head_roll=args.roll)
    vol, origin = evaluate(kw, args.seed, args.voxel)
    print(f"sdf {vol.shape} in {time.time() - t:.0f}s")
    m = to_mesh(vol, origin, args.voxel)
    print(f"raw mesh {len(m.faces)} tris")

    trimesh.smoothing.filter_taubin(m, iterations=6)
    lods = [decimate(m, int(x)) for x in args.lods.split(",")]
    for i, lod in enumerate(lods):
        path = os.path.join(args.out, f"{args.name}_LOD{i}.obj")
        write_obj(lod, path, f"{args.name}_LOD{i}")
        print(f"{path}: {len(lod.faces)} tris")

    pv = args.preview or args.out
    os.makedirs(pv, exist_ok=True)
    head = VeiledStatue(**kw).head_c
    render(lods[0], os.path.join(pv, f"{args.name}_front.png"), yaw=0)
    render(lods[0], os.path.join(pv, f"{args.name}_three_quarter.png"), yaw=-35)
    render(lods[0], os.path.join(pv, f"{args.name}_upper.png"), yaw=-25, target=head + [0, -0.3, 0], zoom=2.4)
    render(lods[0], os.path.join(pv, f"{args.name}_face.png"), yaw=-20, target=head + [0, -0.02, 0], zoom=7.0)
    print(f"done in {time.time() - t:.0f}s")


if __name__ == "__main__":
    main()
